# Generated by Django 5.2.10 on 2026-01-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_code',
            new_name='key',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created_at',
        ),
    ]
