# Generated by Django 5.2.10 on 2026-01-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gameimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player1_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='player2_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='key',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
