# Generated by Django 5.2.10 on 2026-01-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_room_player1_ready_room_player2_ready_alter_room_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player1_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='player2_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
