# Generated by Django 5.2.10 on 2026-01-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_room_player1_image_room_player2_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
